# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 22:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', models.TextField(max_length=5000, null=True)),
                ('venue_name', models.CharField(max_length=40)),
                ('venue_address', models.CharField(max_length=40)),
                ('venue_city', models.CharField(max_length=40)),
                ('venue_postcode', models.CharField(max_length=10)),
                ('contact_details', models.TextField(max_length=120)),
                ('ticket_link', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
