# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20160616_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='event',
            name='width_field',
        ),
        migrations.AddField(
            model_name='event',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.upload_location),
        ),
    ]
