# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20160620_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(null=True, upload_to=events.models.upload_location),
        ),
    ]
