# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.University'),
        ),
    ]
