# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_uni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='uni',
            field=models.ManyToManyField(to='events.Uni'),
        ),
    ]
