# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_event_auth0_favourite_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contact_details',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
    ]
