# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20160901_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='feed_poster',
            field=models.ImageField(null=True, upload_to=events.models.upload_location_feed),
        ),
    ]
