# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_event_feed_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='feed_poster',
            field=models.ImageField(blank=True, null=True, upload_to=events.models.upload_location_feed),
        ),
    ]
