# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-18 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20161107_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue_address',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_city',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
